name: AppEngine
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build-deploy:
    name: Build Docker container, Deploy to App Engine
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    # Build Docker Image
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag ${{ github.event.repository.name }}

    # Authenticate job against GCP account
    - name: Authenticate
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/945819825863/locations/global/workloadIdentityPools/container-pool/providers/container-provider'
        service_account: 'container-service@dopewars-shammils.iam.gserviceaccount.com'

    # Deploy
    - name: Deploy
      uses: 'google-github-actions/deploy-appengine@v0'
      with:
        deliverables: 'app.yaml'
