name: Default
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
    
    # Build Docker Image
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    # Authenticate job against GCP account
    - name: Authenticate
      uses: 'google-github-actions/auth@v0.6.0'
      with:
        workload_identity_provider: 'projects/945819825863/locations/global/workloadIdentityPools/container-pool/providers/container-provider'
        service_account: 'container-service@dopewars-shammils.iam.gserviceaccount.com'
    
