name: Default
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build-publish-deploy:
    name: Build Docker container, Publish to GCR and Deploy to Cloud Run
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    # Build Docker Image
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag ${{ github.event.repository.name }}

    # Authenticate job against GCP account
    - name: Authenticate
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/945819825863/locations/global/workloadIdentityPools/container-pool/providers/container-provider'
        service_account: 'container-service@dopewars-shammils.iam.gserviceaccount.com'

    # Install and setup gcloud. should probably do this earlier
    - name: Set up GCloud SDK
      uses: 'google-github-actions/setup-gcloud@v0'

    # DEBUG: See if this is actually working
    - name: DEBUG
      run: |-
        gcloud iam service-accounts list

    # Publish Docker Container to Google Cloud Registry
    # log dir specified to work around permissions issue https://issuetracker.google.com/issues/134928412?pli=1
    # storage bucket must be created manually for this to work
    - name: Publish Container
      run: gcloud builds submit --tag gcr.io/dopewars-shammils/${{ github.event.repository.name }} --gcs-log-dir=gs://container-service-logs

    # Deploy Image to Cloud Run
    # <un>authenticated traffic cannot be altered from CI
    - name: Deploy
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        service: '${{ github.event.repository.name }}'
        image: 'gcr.io/dopewars-shammils/${{ github.event.repository.name }}'
        region: 'us-central1'

    # DEBUG Show output of Deploy(doesnt work)
    - name: DEBUG Deploy
      run: 'echo ${{ steps.deploy.outputs.url }}'
