name: Default
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
    
    #Build Docker Image
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    
