name: Default
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build-publish-deploy:
    name: Build Docker container, Publish to GCR and Deploy to Cloud Run
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
    
    # Build Docker Image
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag ${{ github.event.repository.name }}
      
    # Authenticate job against GCP account
    - name: Authenticate
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/945819825863/locations/global/workloadIdentityPools/container-pool/providers/container-provider'
        service_account: 'container-service@dopewars-shammils.iam.gserviceaccount.com'
    
    # Install and setup gcloud. should probably do this earlier
    - name: Set up GCloud SDK
      uses: 'google-github-actions/setup-gcloud@v0'
      
    # DEBUG: See if this is actually working
    - name: DEBUG
      run: |-
        gcloud iam service-accounts list
    
    # Publish Docker Container to Google Cloud Registry
    - name: Publish Container
      run: gcloud builds submit --tag gcr.io/dopewars.shammils/${{ github.event.repository.name }}
